#!/usr/bin/env ruby
# frozen_string_literal: true

# add lib to libpath (only needed when running from the sources)
require 'pathname'
lib_path = File.expand_path('../../lib', Pathname.new(__FILE__).realpath)
$LOAD_PATH.unshift lib_path unless $LOAD_PATH.include?(lib_path)

STDOUT.sync = true

require 'wdbomber'

unless ARGV[0]
  puts "wdbomber URL iterations concurrency actions rampup"
  exit 1
end

endpoint = ARGV[0]
iterations = ARGV[1] ? Integer(ARGV[1]) : 0
concurrency = ARGV[2] ? Integer(ARGV[2]) : 1
actions = ARGV[3] ? Integer(ARGV[3]) : 1
rampup = ARGV[4] ? Integer(ARGV[4]) : nil

Wdbomber.run! endpoint, iterations: iterations, concurrency: concurrency, actions: actions, rampup: rampup
