#!/usr/bin/env ruby
# frozen_string_literal: true

# add lib to libpath (only needed when running from the sources)
require 'pathname'
lib_path = File.expand_path('../../lib', Pathname.new(__FILE__).realpath)
$LOAD_PATH.unshift lib_path unless $LOAD_PATH.include?(lib_path)

STDOUT.sync = true

require 'wdbomber'

endpoint = ARGV[0]
iterations = ARGV[1] ? Integer(ARGV[1]) : 0
concurrency = ARGV[2] ? Integer(ARGV[2]) : 1

Wdbomber.run! endpoint, iterations: iterations, concurrency: concurrency
